AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'spec/spec_helper.rb'
    - 'config/puma.rb'
    - 'config/initializers/devise.rb'
    - 'config/initializers/money.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiteralsInInterpolation:
    EnforcedStyle: single_quotes

Style/StringLiterals:
  Enabled: true

Style/StructInheritance:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
